nelmio_api_doc:
    documentation:
        info:
            title: Zoo API
            description: This is a an REST API for a zoo management
            version: 1.0.0
        tags:
            - name: Token 
              description: 
        paths:
            /api/login:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token
                    summary: Log in to get the JWT token
                    security: []
                    requestBody:
                        description: Credentials
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: The JWT token
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
            /api/refresh-token:
                post:
                    operationId: postRefreshToken
                    tags:
                        - Token
                    summary: Refresh the JWT token
                    security: []
                    requestBody:
                        description: RefreshToken
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/RefreshToken'
                    responses:
                        '200':
                            description: The JWT token
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
        components:
            schemas:
                RefreshToken:
                    type: object
                    properties:
                        refresh_token:
                            type: string
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: truet
                        refresh_token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: demo@zoo.org
                        password:
                            type: string
                            default: password
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
