services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    environment:
      - DATABASE_URL=mysql://root:docker1234@mysql:3306/zoodb
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
      - uploads_data:/var/www/html/public/uploads
    expose:
      - 9000
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - cache_data:/var/www/html/var
      - .:/var/www/html
    ports:
      - "9000:80"
      - "8443:443"
    depends_on:
      - app
  mysql:
      image: mysql:8.0
      container_name: mysql
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: docker1234
        MYSQL_DATABASE: zoodb
      volumes:
        - mysql_data:/var/lib/mysql
        - ./mysql/zoodb.sql:/docker-entrypoint-initdb.d/zoodb.sql
      ports:
        - "8306:3306"

volumes:
  mysql_data:
  cache_data:
  uploads_data: