controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_routes:
    resource: '../src/Controller/'
    type: attribute
    prefix: /api

api_login_check:
    path: /api/login

uploads_path:
    path: /uploads/{fileName}
    defaults: { _controller: null }

index_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app.swagger_ui
        permanent: true

