name: Zoo API Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mongodb, mbstring, xml, ctype, iconv
        
    - name: Validate composer.json
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate JWT Keys
      run: |
        mkdir -p config/jwt
        openssl genpkey -out config/jwt/private.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096 -pass pass:${{ secrets.JWT_PASSPHRASE }}
        openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout -passin pass:${{ secrets.JWT_PASSPHRASE }}

    - name: Set up environment
      run: |
        echo "APP_ENV=prod" >> .env.local
        echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env.local
        echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env.local
        echo "JWT_PASSPHRASE=${{ secrets.JWT_PASSPHRASE }}" >> .env.local

    - name: Clear and warmup cache
      run: |
        APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
        APP_ENV=prod APP_DEBUG=0 php bin/console cache:warmup 